name: Test and create Docker image

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build shadow JAR
        run: ./gradlew shadowJar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload .jar file
        uses: actions/upload-artifact@v4
        with:
          name: transitlog-apc-archive-sink.jar
          path: build/libs/transitlog-apc-archive-sink.jar
          retention-days: 1
  build-develop-docker-image:
    needs: test
    runs-on: ubuntu-latest
    # Run only on develop branch
    steps:
      - uses: actions/checkout@v4
      - name: Download .jar file
        uses: actions/download-artifact@v4
        with:
          name: transitlog-apc-archive-sink.jar
          path: build/libs
      - name: Build and publish develop Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: hsldevcom/transitlog-apc-archive-sink
          username: ${{ secrets.TRANSITLOG_DOCKERHUB_USER  }}
          password: ${{ secrets.TRANSITLOG_DOCKERHUB_TOKEN }}
          tags: develop
  build-release-docker-image:
    needs: test
    runs-on: ubuntu-latest
    # Run only for tagged commits
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Download .jar file
        uses: actions/download-artifact@v4
        with:
          name: transitlog-apc-archive-sink.jar
          path: build/libs
      - name: Build and publish release Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: hsldevcom/transitlog-apc-archive-sink
          username: ${{ secrets.TRANSITLOG_DOCKERHUB_USER  }}
          password: ${{ secrets.TRANSITLOG_DOCKERHUB_TOKEN }}
          tag_semver: true